name: Generate gRPC Stubs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-stubs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java (для grpc-java плагина)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install protoc (Protocol Buffers Compiler)
        uses: arduino/setup-protoc@v3

      - name: Install Python gRPC plugin
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install grpcio grpcio-tools

      - name: Download protoc-gen-grpc-java JAR
        run: |
          curl -sSL https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.56.0/protoc-gen-grpc-java-1.56.0.jar -o /usr/local/bin/protoc-gen-grpc-java.jar
          echo '#!/bin/bash' | tee /usr/local/bin/protoc-gen-grpc-java
          echo 'exec java -jar /usr/local/bin/protoc-gen-grpc-java.jar "$@"' >> /usr/local/bin/protoc-gen-grpc-java
          chmod +x /usr/local/bin/protoc-gen-grpc-java

      - name: Generate Python gRPC code
        run: |
          mkdir -p proto/generated/python
          python3 -m grpc_tools.protoc \
            -Iproto \
            --python_out=proto/generated/python \
            --grpc_python_out=proto/generated/python \
            proto/*.proto

      - name: Generate Java gRPC code
        run: |
          mkdir -p proto/generated/java
          protoc \
            --proto_path=proto \
            --java_out=proto/generated/java \
            --grpc-java_out=proto/generated/java \
            proto/*.proto

      - name: Commit and push generated code
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add proto/generated/
          git diff --quiet && echo "No changes to commit" || git commit -m "Auto-generated gRPC stubs"
          git push